# AI Tools - Complete Performance Optimizer (Admin)
# For NVIDIA Quadro P1000 on Windows 11
# Run as Administrator for full system optimization
# ============================================================

param(
    [switch]$Help
)

if ($Help) {
    Write-Host "`nUsage: .\optimize-admin.ps1 [-Help]" -ForegroundColor Cyan
    Write-Host "`nOptions:" -ForegroundColor White
    Write-Host "  -Help    Show this help message`n" -ForegroundColor Gray
    exit
}

# Check if running as Administrator
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if (-not $isAdmin) {
    Write-Host "`n[ERROR] This script must be run as Administrator!" -ForegroundColor Red
    Write-Host "`nRight-click PowerShell and select 'Run as Administrator'" -ForegroundColor Yellow
    Write-Host "Then run: .\ai-tools\optimize-admin.ps1`n" -ForegroundColor Gray
    exit 1
}

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "  AI Tools - Admin Performance Optimizer" -ForegroundColor Cyan
Write-Host "  For: NVIDIA Quadro P1000 (4GB VRAM)" -ForegroundColor Cyan
Write-Host "  Running as: ADMINISTRATOR" -ForegroundColor Green
Write-Host "========================================`n" -ForegroundColor Cyan

# 1. Set Ollama Environment Variables (User)
Write-Host "[1/6] Configuring Ollama (User)..." -ForegroundColor Yellow

$ollamaEnvPath = "$env:USERPROFILE\.ollama\.env"
$ollamaEnvContent = @"
# Ollama Environment for Quadro P1000
# Auto-generated by optimize-admin.ps1
OLLAMA_MAX_VRAM=4294967296
OLLAMA_NUM_GPU=99
OLLAMA_GPU_LAYERS=99
OLLAMA_CONTEXT_LENGTH=4096
OLLAMA_BATCH_SIZE=512
OLLAMA_KEEP_ALIVE=24h
"@

Set-Content -Path $ollamaEnvPath -Value $ollamaEnvContent -Force
Write-Host "  [OK] Created/Updated Ollama .env" -ForegroundColor Green

# 2. Set System Environment Variables (Machine - requires Admin)
Write-Host "`n[2/6] Setting SYSTEM environment variables (Admin)..." -ForegroundColor Yellow

[Environment]::SetEnvironmentVariable("OLLAMA_MAX_VRAM", "4294967296", "Machine")
[Environment]::SetEnvironmentVariable("OLLAMA_NUM_GPU", "99", "Machine")
[Environment]::SetEnvironmentVariable("OLLAMA_GPU_LAYERS", "99", "Machine")
Write-Host "  [OK] Machine environment variables set" -ForegroundColor Green
Write-Host "  Note: Requires restart for some applications" -ForegroundColor Gray

# 3. Set User Environment Variables
Write-Host "`n[3/6] Setting USER environment variables..." -ForegroundColor Yellow

[Environment]::SetEnvironmentVariable("OLLAMA_MAX_VRAM", "4294967296", "User")
[Environment]::SetEnvironmentVariable("OLLAMA_NUM_GPU", "99", "User")
[Environment]::SetEnvironmentVariable("OLLAMA_GPU_LAYERS", "99", "User")
[Environment]::SetEnvironmentVariable("OLLAMA_CONTEXT_LENGTH", "4096", "User")
[Environment]::SetEnvironmentVariable("OLLAMA_BATCH_SIZE", "512", "User")
Write-Host "  [OK] User environment variables set" -ForegroundColor Green

# 4. GPU Detection and Info
Write-Host "`n[4/6] Detecting NVIDIA GPU..." -ForegroundColor Yellow

$gpu = Get-WmiObject Win32_VideoController | Where-Object { $_.Name -like "*NVIDIA*" }
if ($gpu) {
    Write-Host "  [OK] GPU: $($gpu.Name)" -ForegroundColor Green
    Write-Host "      Driver Version: $($gpu.DriverVersion)" -ForegroundColor Gray
    Write-Host "      Video Processor: $($gpu.VideoProcessor)" -ForegroundColor Gray
    Write-Host "      Adapter RAM: $([math]::Round($gpu.AdapterRAM / 1MB, 2)) MB" -ForegroundColor Gray
    
    # Check driver age
    $driverDate = [Management.ManagementDateTimeConverter]::ToDateTime($gpu.DriverDate)
    $daysOld = (New-TimeSpan -Start $driverDate -End (Get-Date)).Days
    Write-Host "      Driver Date: $($driverDate.ToString('yyyy-MM-dd')) ($daysOld days old)" -ForegroundColor Gray
    
    if ($daysOld -gt 90) {
        Write-Host "  [!] Driver is older than 90 days - consider updating" -ForegroundColor Yellow
    }
} else {
    Write-Host "  [!] No NVIDIA GPU detected" -ForegroundColor Yellow
}

# 5. Check Running Processes
Write-Host "`n[5/6] Checking AI-related processes..." -ForegroundColor Yellow

$ollamaProcess = Get-Process -Name "ollama" -ErrorAction SilentlyContinue
$lmStudioProcess = Get-Process -Name "lm-studio" -ErrorAction SilentlyContinue

if ($ollamaProcess) {
    Write-Host "  [OK] Ollama is running" -ForegroundColor Green
    Write-Host "      Restart required for new settings to apply" -ForegroundColor Yellow
} else {
    Write-Host "  [i] Ollama is not running" -ForegroundColor Gray
}

if ($lmStudioProcess) {
    Write-Host "  [OK] LM Studio is running" -ForegroundColor Green
} else {
    Write-Host "  [i] LM Studio is not running" -ForegroundColor Gray
}

# 6. Create Quick Launch Scripts
Write-Host "`n[6/6] Creating quick launch scripts..." -ForegroundColor Yellow

$toolsPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$launcherPath = "$toolsPath\launch-optimized.ps1"

$launcherContent = @"
# Quick Launch - Optimized AI Tools
# Starts Ollama with optimized settings

Write-Host "`nStarting Ollama with optimized settings..." -ForegroundColor Cyan
Write-Host "Press Ctrl+C to stop`n" -ForegroundColor Gray

# Set environment for this session
`$env:OLLAMA_MAX_VRAM = "4294967296"
`$env:OLLAMA_NUM_GPU = "99"
`$env:OLLAMA_GPU_LAYERS = "99"
`$env:OLLAMA_CONTEXT_LENGTH = "4096"
`$env:OLLAMA_BATCH_SIZE = "512"

# Start Ollama
& ollama serve
"@

Set-Content -Path $launcherPath -Value $launcherContent -Force
Write-Host "  [OK] Created: $launcherPath" -ForegroundColor Green

# Summary
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "  Optimization Complete!" -ForegroundColor Green
Write-Host "========================================`n"

Write-Host "What was done:" -ForegroundColor White
Write-Host "  [OK] Ollama .env file created/updated" -ForegroundColor Green
Write-Host "  [OK] System environment variables set (Machine)" -ForegroundColor Green
Write-Host "  [OK] User environment variables set" -ForegroundColor Green
Write-Host "  [OK] Quick launch script created" -ForegroundColor Green

Write-Host "`nNext Steps:" -ForegroundColor White
Write-Host "  1. RESTART your computer (for system env vars to apply)" -ForegroundColor Yellow
Write-Host "  2. Or restart Ollama: ollama serve" -ForegroundColor Gray
Write-Host "  3. Open LM Studio and apply manual settings:" -ForegroundColor Gray
Write-Host "     - GPU Offload: MAX" -ForegroundColor Gray
Write-Host "     - Context: 4096" -ForegroundColor Gray
Write-Host "     - Batch: 512" -ForegroundColor Gray
Write-Host "  4. Test with: /count in LM Studio chat" -ForegroundColor Gray

Write-Host "`nQuick Launch Commands:" -ForegroundColor White
Write-Host "  .\ai-tools\launch-optimized.ps1  - Start Ollama optimized" -ForegroundColor Cyan
Write-Host "  ollama serve                      - Start Ollama normal" -ForegroundColor Cyan

Write-Host "`nExpected Performance (Quadro P1000):" -ForegroundColor White
Write-Host "  3B model (Q4_K_M): ~15-20 tokens/sec" -ForegroundColor Gray
Write-Host "  7B model (Q4_K_M): ~5-8 tokens/sec" -ForegroundColor Gray
Write-Host "  7B model (Q2_K):   ~10-12 tokens/sec" -ForegroundColor Gray

Write-Host "`nDone!`n" -ForegroundColor Green
